name: CMake Build Matrix

on: [pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
        - {
            name: "Ubuntu Latest GCC", artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }
        - {
            name: "macOS Latest Clang", artifact: "macOS.tar.xz",
            os: macos-latest,
            cc: "clang", cxx: "clang++"
          }

    steps:
      - name: Setup vcvars
        if: ${{ matrix.config.environment_script != "" }}
        run: ${{ matrix.config_environment_script }}

      - uses: actions/checkout@v1
      - name: Print environment
        run: echo "${{ matrix.config.name }} ${{ matrix.build_type }}"

      - name: Configure and Build
        uses: lukka/run-cmake@v2.5
        env:
          CXX: ${{ matrix.config.cxx }}
          CC: ${{ matrix.config.cc }}
      