# This is a basic workflow to help you get started with Actions



name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: apt helper action
      run: sudo apt-get install -y xorg-dev
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: compile-with-clang
      uses: lukka/run-cmake@v2.5
      env:
        CXX: clang++-9
        CC: clang-9
      with:
        buildDirectory: "build" # optional, default is ${{ github.workspace }}/../../_temp
        
    - name: compile-with-gcc
      uses: lukka/run-cmake@v2.5
      env:
        CXX: g++-8
        CC: gcc-8
      with:
        buildDirectory: "build_gcc" # optional, default is ${{ github.workspace }}/../../_temp
        
    
